interaction:
  - name: "ask_actively"
    class_name: "verl.interactions.askActively_interaction.AskActivelyInteraction"
    config:
      # 奖励策略（可按需改）
      reward_policy:
        accept_reward: 1.0
        rejection_cost: -1.0
        clarifying_question_cost: -0.3

      # 用户模拟器的上下文截断
      max_history_turns: 6

      # 外部 LLM API 配置（请填写 base_url / model；key_env 可保持默认）
      api:
        base_url: "https://zjuapi.com/v1"        # 例如: https://api.openai.com/v1/chat/completions
        model: ""           # 例如: gpt-4o-mini
        key_env: "sk-9NHRzu99nW5jhDMNqFrkAQf85qhF5l0nzqesnEYaBkkS3r6S" #USER_LLM_API_KEY"
        timeout: 60.0
        extra_headers: {}
        extra_body: {}
  # 如需同时启用其它交互器，可在下方继续追加条目（示例：GSM8K 校验交互）
  # - name: "gsm8k"
  #   class_name: "verl.interactions.gsm8k_interaction.Gsm8kInteraction"
  #   config: {}

